services:
  xrpd:
    image: xxrpd
    build: build/xxrpd
    container_name: xxrpd
    ports:
      - 3389:3389
    volumes:
      - home:/home
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro
#      - /home/CHANGETOUSER:/home/CHANGETOUSER/home
    environment:
      XXRDP_USER: "CHANGETOUSER"
    restart: 'unless-stopped'

volumes:
  home:
